[package]
name = "atc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mint = "^0.5.6"
ggez = "^0.6.1"
# nalgebra = { version = "^0.29", features = ["convert-mint"] }